name: k8s Deployment
run-name: deploying from ${{ inputs.repo }} to ${{ inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: environment
  
permissions: write-all

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - id: identify
        run: |
            echo "deplying to production"
            echo "S3_BUCKET=ding-tenant-app-ios-certificates-prod" >> $GITHUB_OUTPUT
    outputs:
      ENVIRONMENT: ${{ steps.identify.outputs.ENVIRONMENT }}
      S3_BUCKET: ${{ steps.identify.outputs.S3_BUCKET }}

  deployment:
    runs-on: ${{ matrix.runner }}
    needs: set-env
    strategy:
      fail-fast: false
      matrix:
        target: ["ios", "android"]
        include:
          - target: android
            runner: ubuntu-22.04
          - target: ios
            runner: macos-12    
    steps:
      - name: create Matchfile
        working-directory: ding-tenant-app
        run: |
          mkdir fastlane
        
          echo s3_bucket=$s3 > ./fastlane/Matchfile
    
      - name: Setting s3 bucket for fastlane
        working-directory: ding-tenant-app
        run: |
            if [[ "$OSTYPE" == "darwin"* ]]; then
              sed -i '' 's/\$s3bucket/=("\${{ needs.set-env.outputs.S3_BUCKET }}")'/g ./fastlane/Matchfile
            else # assume it is Ubuntu
              sed -i 's/\$s3bucket/=("\${{ needs.set-env.outputs.S3_BUCKET }}")'/g ./fastlane/Matchfile
            fi
            
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1            
