name: k8s Deployment
run-name: deploying from ${{ inputs.repo }} to ${{ inputs.environment }}
on:
  workflow_dispatch:
  
permissions: write-all

jobs:
  deployServices:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Run POSTMAN collection
        continue-on-error: true
        id: postman
        run: |
          export TIME=$(TZ=Asia/Jerusalem date +%H:%M:%S.%3N-%d.%m.%Y)
          echo "RESULT_FILE=$TIME-report.html" >> $GITHUB_OUTPUT
          echo $TIME

