name: k8s Deployment
run-name: deploying from ${{ inputs.repo }} to ${{ inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: environment
  
permissions: write-all

jobs:
  deployServices:
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      STOPDEPLOY: "test"
    steps:
      - id: identify
        run: |
            echo test env in identify step:  ${{ env.TEST_ENV }}
            echo "STOPDEPLOY=master" >> $GITHUB_OUTPUT
            
      - id: test
        run: |
          echo test env in identify step: ${{ env.TEST_ENV }}
          echo "STOPDEPLOY=main" >> $GITHUB_OUTPUT
          
    outputs:
      STOPDEPLOY: ${{ env.TEST_ENV }}

  deployment:
    needs: deployServices
    runs-on: ubuntu-latest
    steps:
      - name: print env
        run: |
          echo "should print main"
          echo ${{ needs.deployServices.outputs.STOPDEPLOY }}
