name: k8s Deployment
run-name: deploying from ${{ inputs.repo }} to ${{ inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: environment
  
permissions: write-all

jobs:
  deployServices:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - id: identify
        run: |
            echo "deplying to production"
            echo "STOPDEPLOY=no" >> $GITHUB_OUTPUT
    outputs:
      STOPDEPLOY: ${{ steps.identify.outputs.STOPDEPLOY }}

  deployment:
    needs: deployServices
    runs-on: ubuntu-latest
    if: ${{ contains(needs.deployServices.result, 'success') && needs.deployServices.outputs.STOPDEPLOY == 'no' }}
    steps:
      - name: print env
        run: |
          echo "here"
